#!/usr/bin/env bash
# Writes VITE_SF_INSTANCE_URL and VITE_SF_ACCESS_TOKEN to .env.local from the
# Salesforce CLI session (org alias: forticloud-cursor by default).
# Run once per session — SF tokens expire after ~2 hours:
#   bash scripts/sf-setup-env.sh
# or:
#   SF_TARGET_ORG=my-other-alias bash scripts/sf-setup-env.sh
#
# .env.local is gitignored by default in Vite projects — do NOT commit it.

set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TARGET_ORG="${SF_TARGET_ORG:-forticloud-cursor}"

echo "Fetching Salesforce credentials for org: ${TARGET_ORG} ..."
JSON="$(sf org display --target-org "${TARGET_ORG}" --json)"

INSTANCE_URL="$(node -e "const j=JSON.parse(process.argv[1]); process.stdout.write(j.result.instanceUrl.replace(/\\/$/,''));" "${JSON}")"
ACCESS_TOKEN="$(node -e "const j=JSON.parse(process.argv[1]); process.stdout.write(j.result.accessToken);" "${JSON}")"

ENV_FILE="${ROOT}/.env.local"

cat > "${ENV_FILE}" <<EOF
# Auto-generated by scripts/sf-setup-env.sh — do NOT commit
# Re-run after token expiry (~2 h): bash scripts/sf-setup-env.sh
VITE_SF_INSTANCE_URL=${INSTANCE_URL}
VITE_SF_ACCESS_TOKEN=${ACCESS_TOKEN}
# Dev proxy reads fresh tokens from \`sf\` when this is set (see vite.config.ts)
VITE_SF_ORG_ALIAS=${TARGET_ORG}
EOF

echo "Wrote ${ENV_FILE}"
echo "  VITE_SF_INSTANCE_URL=${INSTANCE_URL}"
echo "  VITE_SF_ACCESS_TOKEN=<redacted>"
